### ISSUE TITLE
[Feat] Add Bluesky as social platform option

### ISSUE THREAD

**Issue by ChristianSko** [FlineDev/LinksKit#4]
## Problem Statement
Bluesky seems to be raising in popularity very fast and there is no option here to add it as social platform

## Suggested Solution
Add Bluesky as an option just like Twitter

## Additional Considerations
Nope, all good! Thanks for all these SDKs they are truly a breeze to use!  =)

**Comment by ChristianSko** [comment]
Created a PR for it here:
https://github.com/FlineDev/LinksKit/pull/5

**Comment by Jeehut** [comment]
@ChristianSko As you said that #5 was your first open-source contribution, here's a tip:

If you write something like "Fixes #4" or "Implements #4" in the PR description, the related issue will auto-close when the PR is merged. Just a convenience for your future contributions. 😊 

Closing now, thanks again for fixing this! 🙏

**Comment by ChristianSko** [comment]
Duly noted, @Jeehut, that is really cool; I didn't know! Thanks for sharing!

I'm looking forward to doing more.

Actually, thank you for all these SDKs; they are helping me a lot lately. I'm just happy I can give back somehow.😄
